### ISSUE TITLE
API Error Message 18

### ISSUE THREAD

**Issue by 03397** [MGaetan89/ShowsRage#14]
Every time I use showsrage to connect to Sickrage I am getting an error message in Sickrage logs saying 

2015-09-25 16:11:30 TORNADO :: API :: error 18
2015-09-25 16:11:06 TORNADO :: API :: error 18
2015-09-25 16:10:54 TORNADO :: API :: error 18

I do not have any actual problem in connecting it is just that error message.

**Comment by MGaetan89** [comment]
I am not able to reproduce this.
Did you notice that this error happens only when you are in a specific part of the application?
Are you using https (and maybe self-signed certificate)?

**Comment by MGaetan89** [comment]
I found the place where SickRage logs these errors, but it is not really helpful.
Can you enable debug in SickRage (in _Config_ > _General_ > _Advanced Settings_ > _Enable debug_) and tell me if you have more information in the logs?

**Comment by 03397** [comment]
I have make a debug  since the start of using ShowsRage and browsing into some tv shows

2015-09-25 20:40:21 DEBUG    TORNADO :: API :: show.seasons: curKwargs {'season': '4', 'indexerid': '81189'}

2015-09-25 20:40:21 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '81189', 'season': '4', 'cmd': 'show.seasons'}'

2015-09-25 20:40:21 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:21 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: show.seasons: curKwargs {'season': '5', 'indexerid': '81189'}

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '81189', 'season': '5', 'cmd': 'show.seasons'}'

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:20 DEBUG    TORNADO :: Found indexer mapping in cache for show: Breaking Bad

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: show: curKwargs {'indexerid': '81189'}

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '81189', 'cmd': 'show'}'

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: show.seasonlist: curKwargs {'indexerid': '81189'}

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '81189', 'cmd': 'show.seasonlist'}'

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:20 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: sb.getrootdirs: curKwargs {}

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'sb.getrootdirs'}'

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: show.seasons: curKwargs {'season': '3', 'indexerid': '257655'}

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '257655', 'season': '3', 'cmd': 'show.seasons'}'

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:19 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: show.seasons: curKwargs {'season': '4', 'indexerid': '257655'}

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '257655', 'season': '4', 'cmd': 'show.seasons'}'

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:18 DEBUG    TORNADO :: Found indexer mapping in cache for show: Arrow

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: show: curKwargs {'indexerid': '257655'}

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '257655', 'cmd': 'show'}'

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: show.seasonlist: curKwargs {'indexerid': '257655'}

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '257655', 'cmd': 'show.seasonlist'}'

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:18 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:17 DEBUG    TORNADO :: API :: sb.getrootdirs: curKwargs {}

2015-09-25 20:40:17 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'sb.getrootdirs'}'

2015-09-25 20:40:17 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:17 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:16 DEBUG    TORNADO :: API :: show.seasons: curKwargs {'season': '8', 'indexerid': '76290'}

2015-09-25 20:40:16 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '76290', 'season': '8', 'cmd': 'show.seasons'}'

2015-09-25 20:40:16 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:16 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: show.getfanart: curKwargs {'tvdbid': '76290'}

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show.getfanart', 'tvdbid': '76290'}'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: show.seasons: curKwargs {'season': '9', 'indexerid': '76290'}

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '76290', 'season': '9', 'cmd': 'show.seasons'}'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:15 DEBUG    TORNADO :: Found indexer mapping in cache for show: 24

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: show: curKwargs {'indexerid': '76290'}

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '76290', 'cmd': 'show'}'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: show.seasonlist: curKwargs {'indexerid': '76290'}

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '76290', 'cmd': 'show.seasonlist'}'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:15 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

AAKeyError: 18

AA    episode_status_counts_total[status] += 1

AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webapi.py", line 2666, in run

AA    curOutDict = func(curArgs, curKwargs).run()

AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webapi.py", line 205, in call_dispatcher

AA    outDict = _call_dispatcher(args, kwargs)

AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webapi.py", line 135, in get

AATraceback (most recent call last):

2015-09-25 20:40:13 ERROR    TORNADO :: API :: error 18

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: show.stats: curKwargs {'indexerid': '76290'}

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: all kwargs: '{'show.stats_281662.indexerid': '281662', 'show.stats_295515.indexerid': '295515', 'show.stats_266883.indexerid': '266883', 'show.stats_205281.indexerid': '205281', 'show.stats_248837.indexerid': '248837', 'show.stats_281620.indexerid': '281620', 'show.stats_176941.indexerid': '176941', 'show.stats_279121.indexerid': '279121', 'show.stats_260449.indexerid': '260449', 'show.stats_269533.indexerid': '269533', 'show.stats_257655.indexerid': '257655', 'show.stats_95491.indexerid': '95491', 'show.stats_247808.indexerid': '247808', 'show.stats_153021.indexerid': '153021', 'show.stats_282670.indexerid': '282670', 'show.stats_129261.indexerid': '129261', 'show.stats_268592.indexerid': '268592', 'show.stats_279201.indexerid': '279201', 'show.stats_76290.indexerid': '76290', 'show.stats_289590.indexerid': '289590', 'show.stats_266189.indexerid': '266189', 'show.stats_248742.indexerid': '248742', 'show.stats_75340.indexerid': '75340', 'show.stats_292174.indexerid': '292174', 'cmd': 'show.stats_76290|show.stats_257655|show.stats_81189|show.stats_292174|show.stats_205281|show.stats_121361|show.stats_279201|show.stats_247897|show.stats_281620|show.stats_265074|show.stats_281662|show.stats_289590|show.stats_282670|show.stats_248742|show.stats_75340|show.stats_295515|show.stats_248837|show.stats_176941|show.stats_129261|show.stats_247808|show.stats_268592|show.stats_266189|show.stats_279121|show.stats_269533|show.stats_266883|show.stats_95491|show.stats_153021|show.stats_260449', 'show.stats_81189.indexerid': '81189', 'show.stats_121361.indexerid': '121361', 'show.stats_265074.indexerid': '265074', 'show.stats_247897.indexerid': '247897'}'

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: sb.getrootdirs: curKwargs {}

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'sb.getrootdirs'}'

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Dark Matter

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Mr. Robot

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Person of Interest

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Marvel's Daredevil

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: The 100

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Suits

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Sherlock

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: The Vampire Diaries

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Spartacus

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: 24

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Legends (2014)

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Homeland

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Game of Thrones

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Breaking Bad

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: How to Get Away with Murder

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Arrow

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: The Blacklist

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: The Originals

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Vikings

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: The Flash (2014)

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: The Walking Dead

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Falling Skies

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Revenge

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: The Last Ship

2015-09-25 20:40:13 DEBUG    TORNADO :: Found indexer mapping in cache for show: Prison Break

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: shows: curKwargs {'sort': 'name'}

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: all kwargs: '{'sort': 'name', 'cmd': 'shows'}'

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: all args: '()'

2015-09-25 20:40:13 DEBUG    TORNADO :: API :: 192.168.10.1 - gave correct API KEY. ACCESS GRANTED

**Comment by MGaetan89** [comment]
Thank you. That last log contains more helpful information.
From what I can tell, the error is in SickRage, not in ShowsRage.
I will investigate more and fix the issue.

**Comment by MGaetan89** [comment]
I opened an issue on SickRage project. I will keep you inform once it's fixed.

**Comment by 03397** [comment]
Thanks…

**Comment by MGaetan89** [comment]
A new version of SickRage was released yesterday. Can you update and let me know if you still have this error?

**Comment by 03397** [comment]
Yes I have the same error.
On Sep 29, 2015 20:28, Gaëtan Muller notifications@github.com wrote:A new version of SickRage was released yesterday. Can you update and let me know if you still have this error?

**Comment by 03397** [comment]
It seems that this problem is solved after the upgrade of Sickrage.

**Comment by MGaetan89** [comment]
Thanks for the feedback. I'll forward the information to SickRage developers.
