### ISSUE TITLE
Using self signed ssl  certificate does not work 

### ISSUE THREAD

**Issue by nesalkiN** [MGaetan89/ShowsRage#7]
SickBeard throws this in the log when trying to connect using ssl:

2015-09-21 00:49:25 WARNING  SSL Error on 12 ('192.168.1.1', 56762): [Errno 1] _ssl.c:510: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
2015-09-21 00:49:25 ERROR    Uncaught exception
Traceback (most recent call last):
  File "/home/bork/SickRage/tornado/http1connection.py", line 691, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/home/bork/SickRage/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/bork/SickRage/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/bork/SickRage/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/home/bork/SickRage/tornado/http1connection.py", line 166, in _read_message
    quiet_exceptions=iostream.StreamClosedError)
  File "/home/bork/SickRage/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/bork/SickRage/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [Errno 1] _ssl.c:510: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown

Https works great using web browser

**Comment by MGaetan89** [comment]
I will look into this to fix it in the next version.
Thank you for reporting it.

**Comment by MGaetan89** [comment]
This has been fixed an will be available on the Play Store in a few hours.
Let me know if you still have some issues to configure or use ShowsRage.
