### ISSUE TITLE
Improve alternative forks support

### ISSUE THREAD

**Issue by MGaetan89** [MGaetan89/ShowsRage#77]
Possible forks:
- SickRage
- PyMedusa
- SickGear
- SickBeard

**Comment by keithzg** [comment]
This would certainly be appreciated! As it stands, many of the functions work well with SickGear, except that the Shows page is entirely empty---and that kindof kills a lot of the usefulness of the app, alas.

For the record the logcat output at the time goes as follows:

```
10-02 02:02:38.368 27085 27085 W System.err: retrofit.RetrofitError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 5 column 27 path $.data..anime
10-02 02:02:38.368 27085 27085 W System.err:    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:383)
10-02 02:02:38.368 27085 27085 W System.err:    at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
10-02 02:02:38.369 27085 27085 W System.err:    at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
10-02 02:02:38.369 27085 27085 W System.err:    at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
10-02 02:02:38.369 27085 27085 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-02 02:02:38.369 27085 27085 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-02 02:02:38.369 27085 27085 W System.err:    at retrofit.Platform$Android$2$1.run(Platform.java:142)
10-02 02:02:38.369 27085 27085 W System.err:    at java.lang.Thread.run(Thread.java:919)
10-02 02:02:38.369 27085 27085 W System.err: Caused by: retrofit.converter.ConversionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 5 column 27 path $.data..anime
10-02 02:02:38.369 27085 27085 W System.err:    at retrofit.converter.GsonConverter.fromBody(GsonConverter.java:67)
10-02 02:02:38.369 27085 27085 W System.err:    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:367)
10-02 02:02:38.369 27085 27085 W System.err:    ... 7 more
10-02 02:02:38.369 27085 27085 W System.err: Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 5 column 27 path $.data..anime
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.Gson.fromJson(Gson.java:810)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.Gson.fromJson(Gson.java:775)
10-02 02:02:38.369 27085 27085 W System.err:    at retrofit.converter.GsonConverter.fromBody(GsonConverter.java:63)
10-02 02:02:38.369 27085 27085 W System.err:    ... 8 more
10-02 02:02:38.369 27085 27085 W System.err: Caused by: java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 5 column 27 path $.data..anime
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1200)
10-02 02:02:38.369 27085 27085 W System.err:    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
10-02 02:02:38.370 27085 27085 W System.err:    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:231)
10-02 02:02:38.370 27085 27085 W System.err:    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
10-02 02:02:38.370 27085 27085 W System.err:    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
10-02 02:02:38.370 27085 27085 W System.err:    ... 16 more
```

I'm going to give it a shot myself, but uhh my track record with Android is an unbroken series of losses ;)
